baseurl = "https://nxskok.github.io/blog/"
publishDir = "docs"
relativeurls = true
languageCode = "en-us"
title = "Ken's Blog"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = "kens-blog-2"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Ken Butler"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/nxskok"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/kenbutler12"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[taxonomies]
  tag = "tags"
  category = "categories"